### ISSUE TITLE
Cuda error in func 'set_constants' at line 134 : invalid device symbol.

### ISSUE THREAD

**Issue by eromoe** [Anthony-Tatowicz/cuda-ethminer#1]
I am using GeForce GTX 1080, but not working...
```
[CUDA]:Using grid size 8192, block size 128

  m  04:11:20|ethminer  Getting work package...
  m  04:11:20|ethminer  Grabbing DAG for #71a56fef…
  ℹ  04:11:31|ethminer  Loading full DAG of seedhash: #3a619bcc…
  m  04:11:31|ethminer  Got work package: #3579708e
  ℹ  04:11:31|cudaminer0  set work to #3579708e, target  #0000000112e0be82
  ℹ  04:11:31|cudaminer0  Initialising miner...
  m  04:11:31|ethminer  Mining on PoWhash #3579708e : 0.00MH/s [A0+0:R0+0:F0]
Using device: GeForce GTX 1080 (Compute 6.1)
  m  04:11:42|ethminer  Mining on PoWhash #3579708e : 0.00MH/s [A0+0:R0+0:F0]
  m  04:11:42|ethminer  Got work package: #467be9e0
Cuda error in func 'set_constants' at line 134 : invalid device symbol.

```

**Comment by fuyufjh** [comment]
Got exactly the same error

**Comment by tatowicz** [comment]
Recheck it I just merged an update, I do not have a 1080 so I can't test it myself.

**Comment by vv111y** [comment]
as per this [bitcointalk](https://bitcointalk.org/index.php?topic=1368785.820) you apparently need to remove ';-gencode arch=compute_61,code=sm_61' from line 

	set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-gencode arch=compute_20,code=sm_20;-gencode arch=compute_30,code=sm_30;-gencode arch=compute_35,code=sm_35;-gencode arch=compute_50,code=sm_50;-gencode arch=compute_52,code=sm_52;-gencode arch=compute_61,code=sm_61)

from this file:
[https://github.com/Genoil/cpp-ethereum/blob/110/libethash-cuda/CMakeLists.txt](https://github.com/Genoil/cpp-ethereum/blob/110/libethash-cuda/CMakeLists.txt)

**Comment by vv111y** [comment]
I have the same problem, got error just a few minutes ago.... 
hmmm, open issue with Genoil
[https://github.com/Genoil/cpp-ethereum/issues/128](https://github.com/Genoil/cpp-ethereum/issues/128)

**Comment by tatowicz** [comment]
I will fork the repo and try a rebuild and create a new branch for you to test.

**Comment by niko328** [comment]
hey,I have the same problem,and I found the version of yours is Genoil 1.0.8 why not try to use master...

**Comment by Obeyed** [comment]
@Anthony-Tatowicz I can verify that the latest Dockerfile works.
The image on dockerhub does not work. I built an image with the Dockerfile from this repo.
I have a GTX 1050Ti.

**Comment by jordanmmck** [comment]
Just wanted to add, I did the same thing as @Obeyed and it worked for me on a GTX 1070.

**Comment by vv111y** [comment]
Can confirm as well.
Helps to read the manual. nvidia-docker supplies the necessary libraries unique to your hardware. 
Therefore we need to build from the dockerfile to get correct drivers + libraries

**Comment by tatowicz** [comment]
So I think this issue is good to go I'm going to close it out if it comes up again open a new issue.
