### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by system123** [Anthony-Tatowicz/cuda-ethminer#3]
Hi,

I am receiving this error
`CUDA error in func 'init' at line 243 : out of memory.`

 When running the docker image as follows:
`nvidia-docker run -it anthonytatowicz/eth-cuda-miner -M`

If I run the follwoing it works and I get the output below:

`nvidia-docker run -it anthonytatowicz/eth-cuda-miner --list-devices`

`Genoil's ethminer 0.9.41-genoil-1.1.7

Forked from github.com/ethereum/cpp-ethereum
CUDA kernel ported from Tim Hughes' OpenCL kernel
With contributions from nicehash, nerdralph, RoBiK and sp_ 

Please consider a donation to:
ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

[CUDA]:
Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1080
	Compute version: 6.1
	cudaDeviceProp::totalGlobalMem: 8504868864
`
Any idea what the issue might be referring to?

**Comment by tatowicz** [comment]
Not enough information here to figure out the issue. Possibly something is broken with bench marking.
