### ISSUE TITLE
incorrect entrypoint on container?

### ISSUE THREAD

**Issue by erhank** [Anthony-Tatowicz/cuda-ethminer#7]
FYI...got this when attempting to run current rev of container:

`docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/cpp-ethereum/build/ethminer/ethminer\\\": stat /cpp-ethereum/build/ethminer/ethminer: no such file or directory\"\n".`

overrode the entry point and looked around noted there's no /cpp-ethereum/ off of root, but there is an ethminer dir with the build hierarchy:

> $ nvidia-docker run -it --entrypoint /bin/bash anthonytatowicz/eth-cuda-miner 
> root@24f2c1010ab0:/# cd ethminer/build/ethminer/
> root@24f2c1010ab0:/ethminer/build/ethminer# ls
> CMakeFiles  Makefile  cmake_install.cmake  ethminer
> root@24f2c1010ab0:/ethminer/build/ethminer# file ethminer 
> ethminer: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=79bb3400096742664566a1b762a19b2838722194, not stripped
> root@24f2c1010ab0:/ethminer/build/ethminer# file /usr/local/bin/ethminer
> /usr/local/bin/ethminer: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=79bb3400096742664566a1b762a19b2838722194, not  stripped

Also found the one in /usr/local/bin which appears to be the same bin

**Comment by tatowicz** [comment]
Thanks for letting me know, the docker hub hook is broken since I changed the name of the github repository, so I have to manually run builds. The current docker hub build is broken as it has yet to be updated. The root issue has been resolved with the addition of a webhook, the updated version is currently building try pulling in some time and retry.
