### ISSUE TITLE
cuda error in func 'cuda_check_cpu_setTarget' at line 41 : unspecified launch failure.

### ISSUE THREAD

**Issue by LordCryptocurrency** [Anthony-Tatowicz/cuda-ethminer#9]
I need help, whoever can help me, I thank you (Sorry, for my English).

I'm mining with 2 Geforce Zotac Extreme 1080TI, and this error message constantly pops up:

cuda error in func 'cuda_check_cpu_setTarget' at line 41 : unspecified launch failure.
GPU #01: result for 00000001 does not validate on CPU
![photo_2018-01-10_17-57-27](https://user-images.githubusercontent.com/30157103/34795840-c9891eec-f63a-11e7-91c2-ca58471ee505.jpg)

**Comment by tatowicz** [comment]
I would ask the guys at ethminer about this, also be sure your drivers and Nvidia docker match.

**Comment by LordCryptocurrency** [comment]
1 - Windows 10 - **updated**
2 - Visual basic C++ - **updated**
3 - Net Framework - **updated**
4 - MSI Afterburner - **updated**
5 - NVidia Drives - **updated**

**Comment by tatowicz** [comment]
Okay I see, so a few things I would like to point out. I wouldn't recommend using windows 10 as it reduces your hash rate by about 10x, also Nvidia docker doesn't support windows and the container requires Nvidia docker to operate properly. My recommendation is to switch to a linux machine. Now with that being said if you would like to test things out on your windows machine look at the ethminer repository and it will describe how to get something up an running on windows for testing.

**Comment by tatowicz** [comment]
Closing this issue, if you have any further question create a new issue or email me.
